spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

  main:
    allow-circular-references: true