DROP TABLE IF EXISTS AUTHORS, GENRES, BOOKS;

CREATE TABLE GENRES
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE AUTHORS
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50)
);

CREATE TABLE BOOKS
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255) UNIQUE NOT NULL,
    PAGES INT NOT NULL,
    AUTHOR_ID BIGINT,
    GENRE_ID BIGINT
);

ALTER TABLE BOOKS
    ADD FOREIGN KEY (AUTHOR_ID)
    REFERENCES AUTHORS(ID);

ALTER TABLE BOOKS
    ADD FOREIGN KEY (GENRE_ID)
    REFERENCES GENRES(ID);
