spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: developer

    flyway:
        url: jdbc:postgresql://localhost:5432/postgres
        user: postgres
        password: developer

    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none

    show-sql: true
