INSERT INTO GENRES (NAME)
VALUES ('TEST_GENRE_1');

INSERT INTO AUTHORS (FIRST_NAME, LAST_NAME)
VALUES ('FIRST_NAME_1', 'LAST_NAME_1');

INSERT INTO BOOKS (TITLE, PAGES, AUTHOR_ID, GENRE_ID)
VALUES ('TEST_BOOK_1',
        999,
        (SELECT ID FROM AUTHORS A WHERE A.FIRST_NAME = 'FIRST_NAME_1' AND A.LAST_NAME = 'LAST_NAME_1'),
        (SELECT ID FROM GENRES G WHERE G.NAME = 'TEST_GENRE_1'));
