spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
  main:
    allow-circular-references: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.library.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

