spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: developer

    flyway:
        url: jdbc:postgresql://localhost:5432/postgres
        user: postgres
        password: developer

    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none

    properties:
        hibernate:
            enable_lazy_load_no_trans: true

    show-sql: true

    main:
        allow-circular-references: true
